export const ALL_BLOGDETAILS_REQUEST = "ALL_BLOGDETAILS_REQUEST";
export const ALL_BLOGDETAILS_SUCCESS = "ALL_BLOGDETAILS_SUCCESS";

export const SINGLE_POST_DETAILS_REQUEST = "SINGLE_POST_DETAILS_REQUEST";
export const SINGLE_POST_DETAILS_SUCCESS = "SINGLE_POST_DETAILS_SUCCESS";
