export const ALL_BLOGDETAILS_REQUEST = "ALL_BLOGDETAILS_REQUEST";
export const ALL_BLOGDETAILS_SUCCESS = "ALL_BLOGDETAILS_SUCCESS";

export const SINGLE_POST_DETAILS_REQUEST = "SINGLE_POST_DETAILS_REQUEST";
export const SINGLE_POST_DETAILS_SUCCESS = "SINGLE_POST_DETAILS_SUCCESS";

export const UPDATE_POST_LIKE_REQUEST = "UPDATE_POST_LIKE_REQUEST";
export const UPDATE_POST_LIKE_SUCCESS = "UPDATE_POST_LIKE_SUCCESS";

export const CREATE_POST_DETAILS_REQUEST = "CREATE_POST_DETAILS_REQUEST";
export const CREATE_POST_DETAILS_SUCCESS = "CREATE_POST_DETAILS_SUCCESS";

