export const ALL_MOVIEDETAILS_REQUEST = "ALL_MOVIEDETAILS_REQUEST";
export const ALL_MOVIEDETAILS_SUCCESS = "ALL_MOVIEDETAILS_SUCCESS";

export const SINGLE_MOVIE_DETAILS_REQUEST = "SINGLE_MOVIE_DETAILS_REQUEST";
export const SINGLE_MOVIE_DETAILS_SUCCESS = "SINGLE_MOVIE_DETAILS_SUCCESS";

export const UPDATE_MOVIE_LIKE_REQUEST = "UPDATE_MOVIE_LIKE_REQUEST";
export const UPDATE_MOVIE_LIKE_SUCCESS = "UPDATE_MOVIE_LIKE_SUCCESS";

export const CREATE_MOVIE_DETAILS_REQUEST = "CREATE_MOVIE_DETAILS_REQUEST";
export const CREATE_MOVIE_DETAILS_SUCCESS = "CREATE_MOVIE_DETAILS_SUCCESS";

